### ISSUE TITLE
Pinout for ASUS NODE connector?

### ISSUE THREAD

**Issue by sofakng** [darkspr1te/rog_eye#2]
Do you have the pinout for the ASUS NODE connector?

It looks like we just need SDA, SCL, 3.3V, GND, and EN.  I've researched this a bit but can't quite figure out how the pins are mapped.

**Comment by darkspr1te** [comment]
i think this might help, https://www.techpowerup.com/forums/threads/asus-node-replaces-rog_ext.257606/

**Comment by sofakng** [comment]
Thanks very much.  I was able to find additional information on the Elmor Labs discord too.

Are you continuing work on this project?  I'm wondering if any of the following is possible using the i2c bus:

- Power on/off
- Reset
- Power and sleep status

**Comment by darkspr1te** [comment]
I've stopped any development on this as the device i was originally using for research I sold.

**Comment by sofakng** [comment]
Got it...  I think the connector was also discontinued.  Thanks for the information and for the work on this project!
